// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56q9rHr8T10dR1KKSqVwgkH464ZySgDQ',
    appId: '1:541009219366:web:28804951cea1922b0f3be7',
    messagingSenderId: '541009219366',
    projectId: 'project-seblak-kacida',
    authDomain: 'project-seblak-kacida.firebaseapp.com',
    databaseURL: 'https://project-seblak-kacida-default-rtdb.firebaseio.com',
    storageBucket: 'project-seblak-kacida.firebasestorage.app',
    measurementId: 'G-9YB61Q7QGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALpZAWPZHdT3Gnf4E6hz7EQEpxRKBS3As',
    appId: '1:541009219366:android:211d28e5a35ed5550f3be7',
    messagingSenderId: '541009219366',
    projectId: 'project-seblak-kacida',
    databaseURL: 'https://project-seblak-kacida-default-rtdb.firebaseio.com',
    storageBucket: 'project-seblak-kacida.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi2aK5GiSMH94fj2zJ06_uvdJQ58QsSVU',
    appId: '1:541009219366:ios:213998e36dd18dc20f3be7',
    messagingSenderId: '541009219366',
    projectId: 'project-seblak-kacida',
    databaseURL: 'https://project-seblak-kacida-default-rtdb.firebaseio.com',
    storageBucket: 'project-seblak-kacida.firebasestorage.app',
    iosBundleId: 'com.example.seblakPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi2aK5GiSMH94fj2zJ06_uvdJQ58QsSVU',
    appId: '1:541009219366:ios:213998e36dd18dc20f3be7',
    messagingSenderId: '541009219366',
    projectId: 'project-seblak-kacida',
    databaseURL: 'https://project-seblak-kacida-default-rtdb.firebaseio.com',
    storageBucket: 'project-seblak-kacida.firebasestorage.app',
    iosBundleId: 'com.example.seblakPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD56q9rHr8T10dR1KKSqVwgkH464ZySgDQ',
    appId: '1:541009219366:web:e1c74f858cd3574f0f3be7',
    messagingSenderId: '541009219366',
    projectId: 'project-seblak-kacida',
    authDomain: 'project-seblak-kacida.firebaseapp.com',
    databaseURL: 'https://project-seblak-kacida-default-rtdb.firebaseio.com',
    storageBucket: 'project-seblak-kacida.firebasestorage.app',
    measurementId: 'G-J9MZ1TZD9R',
  );
}
