// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvJbpCKWl_ofPQ3qHbSQcTeldi9fyWoTo',
    appId: '1:452349470207:web:aa58c95948fa880b8fb3ca',
    messagingSenderId: '452349470207',
    projectId: 'seblak-pos',
    authDomain: 'seblak-pos.firebaseapp.com',
    storageBucket: 'seblak-pos.firebasestorage.app',
    measurementId: 'G-LB64F2SHER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEW6l-FcC-zuKIFycXd69XXkeyEB4SI0E',
    appId: '1:452349470207:android:a319c379b028d1168fb3ca',
    messagingSenderId: '452349470207',
    projectId: 'seblak-pos',
    storageBucket: 'seblak-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7EUOKa84F7Lqg2qrFMHBmq3_SipntEN4',
    appId: '1:452349470207:ios:989db53af0e0024c8fb3ca',
    messagingSenderId: '452349470207',
    projectId: 'seblak-pos',
    storageBucket: 'seblak-pos.firebasestorage.app',
    iosBundleId: 'com.example.seblakPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7EUOKa84F7Lqg2qrFMHBmq3_SipntEN4',
    appId: '1:452349470207:ios:989db53af0e0024c8fb3ca',
    messagingSenderId: '452349470207',
    projectId: 'seblak-pos',
    storageBucket: 'seblak-pos.firebasestorage.app',
    iosBundleId: 'com.example.seblakPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvJbpCKWl_ofPQ3qHbSQcTeldi9fyWoTo',
    appId: '1:452349470207:web:bdcf18535b214f218fb3ca',
    messagingSenderId: '452349470207',
    projectId: 'seblak-pos',
    authDomain: 'seblak-pos.firebaseapp.com',
    storageBucket: 'seblak-pos.firebasestorage.app',
    measurementId: 'G-5QV6GQQLHF',
  );
}
